version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: client-postgres
    environment:
      POSTGRES_DB: clientdb
      POSTGRES_USER: clientuser
      POSTGRES_PASSWORD: clientpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clientuser -d clientdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
