services:
  postgres:
    image: postgres:15-alpine
    container_name: client-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fitness-network
  client-service:
    container_name: client-service
    build: .
    ports:
      - "3000:3000" # HTTP
      - "50522:50522" # gRPC
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@client-postgres:5432/postgres
      - HTTP_PORT=3000
    networks:
      - fitness-network
    depends_on:
      - postgres
  pgadminclient:
    image: dpage/pgadmin4
    container_name: pgadminclient
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - fitness-network
networks:
  fitness-network:
    external: true

volumes:
  postgres_data:
  pgadmin_data:
