import { Test, TestingModule } from '@nestjs/testing';
import { ConflictException, NotFoundException } from '@nestjs/common';
import { ClientService } from './client.service';
import { PrismaService } from '../prisma/prisma.service';
import { UserResponse } from './interfaces/user.interface';
import * as bcrypt from 'bcrypt';
import { PrismaClientKnownRequestError } from '@prisma/client/runtime/library';

// Mock bcrypt
jest.mock('bcrypt', () => ({
  hash: jest.fn().mockResolvedValue('hashedPassword123'),
}));

describe('ClientService', () => {
  let service: ClientService;
  let prismaService: PrismaService;

  let mockUser: UserResponse & { createdAt: Date; updatedAt: Date };
  let mockPrismaService: {
    user: {
      findUnique: jest.Mock;
      create: jest.Mock;
    };
  };

  beforeEach(() => {
    const now = new Date();
    mockUser = {
      id: 'test-user-123',
      firstName: 'John',
      lastName: 'Doe',
      email: 'john.doe@example.com',
      isActive: true,
      createdAt: now,
      updatedAt: now,
    };

    mockPrismaService = {
      user: {
        findUnique: jest.fn().mockResolvedValue(mockUser),
        create: jest.fn().mockImplementation(({ data }) => 
          Promise.resolve({
            ...data,
            password: 'hashedPassword123',
            createdAt: new Date(),
            updatedAt: new Date(),
          })
        ),
      },
    };
  });

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        ClientService,
        {
          provide: PrismaService,
          useValue: mockPrismaService,
        },
      ],
    }).compile();

    service = module.get<ClientService>(ClientService);
    prismaService = module.get<PrismaService>(PrismaService);
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  it('should be defined', () => {
    expect(service).toBeDefined();
  });

  describe('createUser', () => {
    let createUserDto;
    
    beforeEach(() => {
      createUserDto = {
        id: 'new-user-123',
        firstName: 'Test',
        lastName: 'User',
        email: 'new.user@example.com',
        password: 'TestPassword123!',
        isActive: true,
      };
      
      // Reset the mock implementation for create to return the new user
      mockPrismaService.user.create.mockImplementation(({ data }) => 
        Promise.resolve({
          ...data,
          createdAt: new Date(),
          updatedAt: new Date(),
        })
      );
    });

    it('should create a new user', async () => {
      // Mock Prisma to return null (user doesn't exist)
      (mockPrismaService.user.findUnique as jest.Mock).mockResolvedValueOnce(null);
      
      // Mock Prisma create to return the new user with a generated ID
      const mockCreatedUser = {
        id: 'generated-id-123', // This would be generated by the database
        firstName: createUserDto.firstName,
        lastName: createUserDto.lastName,
        email: createUserDto.email,
        password: createUserDto.password, // Password is stored as plain text
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      };
      (mockPrismaService.user.create as jest.Mock).mockResolvedValueOnce(mockCreatedUser);

      const result = await service.createUser(createUserDto);
      
      // Verify the user was created with the correct data
      const createCall = (mockPrismaService.user.create as jest.Mock).mock.calls[0][0];
      
      // The service should not include the ID in the create data
      // as it's generated by the database
      expect(createCall.data).toEqual({
        firstName: createUserDto.firstName,
        lastName: createUserDto.lastName,
        email: createUserDto.email,
        password: createUserDto.password, // Plain text password
        isActive: true,
      });
      
      // The result should match our mock created user (without the password)
      expect(result).toEqual({
        id: mockCreatedUser.id,
        firstName: mockCreatedUser.firstName,
        lastName: mockCreatedUser.lastName,
        email: mockCreatedUser.email,
        isActive: mockCreatedUser.isActive,
      });
      
      // Verify the select clause
      expect(createCall.select).toEqual({
        id: true,
        firstName: true,
        lastName: true,
        email: true,
        isActive: true,
        createdAt: true,
        updatedAt: true,
      });
      
      // The service returns a UserResponse which doesn't include timestamps
      // It should use the ID that was generated by the database (from our mock)
      expect(result).toEqual({
        id: mockCreatedUser.id, // Use the ID from our mock
        firstName: createUserDto.firstName,
        lastName: createUserDto.lastName,
        email: createUserDto.email,
        isActive: true,
      });
    });

    it('should throw ConflictException if email already exists', async () => {
      // Create a plain object that matches the Prisma error structure
      const prismaError = {
        name: 'PrismaClientKnownRequestError',
        code: 'P2002',
        meta: { target: ['email'] },
        message: 'Unique constraint failed on the fields: (email)',
      };
      
      // Mock the create method to reject with the Prisma error
      mockPrismaService.user.create.mockRejectedValueOnce(prismaError);

      // The service should convert this to a ConflictException
      await expect(service.createUser(createUserDto)).rejects.toThrow(ConflictException);
      
      // Verify the user creation was attempted with the correct email
      expect(mockPrismaService.user.findUnique).toHaveBeenCalledWith({
        where: { email: createUserDto.email },
      });
    });
  });

  describe('fetchUser', () => {
    it('should return a user if found', async () => {
      // Mock Prisma to return a user
      jest.spyOn(prismaService.user, 'findUnique').mockResolvedValueOnce({
        ...mockUser,
        password: 'test-password-123',
      });

      const result = await service.fetchUser({email: 'john.doe@example.com', password: 'test-password-123'});
      expect(result).toEqual(expect.objectContaining({
        id: mockUser.id,
        firstName: mockUser.firstName,
        lastName: mockUser.lastName,
        email: mockUser.email,
        isActive: mockUser.isActive,
      }));
      expect(prismaService.user.findUnique).toHaveBeenCalledWith({
        where: { email: 'john.doe@example.com' },
        select: {
          id: true,
          firstName: true,
          lastName: true,
          email: true,
          password: true,
          isActive: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    });

    it('should throw NotFoundException when user is not found', async () => {
      // Mock Prisma to return null (user not found)
      jest.spyOn(prismaService.user, 'findUnique').mockResolvedValueOnce(null);
      
      await expect(service.fetchUser({email: 'nonexistent@example.com', password: 'test'})).rejects.toThrow(
        'User with email nonexistent@example.com not found',
      );
    });
  });
});
